server.port=8080
spring.application.name=mall-gateway
spring.cloud.nacos.discovery.server-addr=localhost:8848

spring.cloud.gateway.server.webflux.routes[0].id=mall-user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://mall-user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**,/role/**

spring.cloud.gateway.server.webflux.routes[1].id=mall-product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://mall-product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/product/**

spring.cloud.gateway.server.webflux.routes[2].id=mall-order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://mall-order-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/order/**